template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output stage/cluster.yaml::ECSCluster
  Namespace: cinco-arclight-stage
  VpcId: {{ var.stage.VPC_ID }}
  SubnetIDs: {{ var.stage.SUBNET_IDS }}
  ContainerImage: !stack_output stage/arclight/build.yaml::ECRRepository
  ContainerPort: 3000
  HealthCheckPath: '/up'
  DBInstanceSecurityGroup: !stack_output stage/arclight/db.yaml::RDSSecurityGroup
sceptre_user_data:
  ContainerEntryPoint: "/rails/bin/docker-entrypoint"
  ContainerCommand:
    - "./bin/rails"
    - "server"
  Description: "Arclight Web Application running in ECS"
  ContainerEnvironment:
    - RAILS_MASTER_KEY: {{ var.stage.RAILS_MASTER_KEY }}
    - REPOSITORY_FILE: "config/repositories-stage.yml"
    - S3_BUCKET: {{ var.stage.S3_BUCKET_NAME }}
    - SOLR_URL: !sub
      - "http://{solr_url}/solr/{core_name}"
      # The load balancer for both followers is created as part of the solr-follower-1 stack
      - solr_url: !stack_output stage/solr/solr-follower-1.yaml::LoadBalancerDNS
        core_name: arclight
    - POSTGRES_HOST: !stack_output stage/arclight/db.yaml::RDSHostName
    - POSTGRES_PORT: 5432
    - POSTGRES_DB: postgres
    - POSTGRES_USER: {{ var.stage.ARCLIGHT_DB_USERNAME }}
    - POSTGRES_PASSWORD: {{ var.stage.ARCLIGHT_DB_PASSWORD }}
  TaskPolicies:
    - !stack_output stage/s3.yaml::Policy
  GrantHttpAccessFromThisServiceTo:
    - !stack_output stage/solr/solr.yaml::LoadBalancerSecurityGroup
