template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-arclight-stage
  Branch: main

sceptre_user_data:
  ECRRepositoryName: cinco-arclight
  BuildEnvironment:
    - SUBNET_IDS: {{ var.stage.SUBNET_IDS }}
  TriggerFilterGroups:
    - - Type: EVENT
        Pattern: PUSH
      - Type: HEAD_REF
        Pattern: ^refs/heads/main$
        ExcludeMatchedPattern: false
      - Type: FILE_PATH
        Pattern: arclight/.*
        ExcludeMatchedPattern: false
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                build:
                  commands:
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com
                    - docker build -t cinco-arclight arclight --file arclight/Dockerfile
                    - docker tag cinco-arclight:latest ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/cinco-arclight:latest
                    - docker push ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/cinco-arclight:latest
                post_build:
                  commands:
                    - docker run -d --name arclight-tail-dev-null cinco-arclight tail -f /dev/null
                    - docker cp arclight-tail-dev-null:/rails/public/assets ./public_assets
                    - aws s3 cp --recursive ./public_assets s3://cinco-stage/arclight_assets/assets
                    - docker stop arclight-tail-dev-null
  additional_policy_statements: |-
    - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !Sub arn:aws:s3:::cinco-stage*
