template:
  path: cloudfront.j2
  type: file
parameters:
  CNAME: dashboard.oac-stg.cdlib.org
  # SSLCertArn:

sceptre_user_data:
  origins:
    - name: arclight
      DomainName: !stack_output stage/arclight/app.yaml::LoadBalancerDNS
