template:
  path: cloudfront.j2
  type: file
parameters:
  NAMESPACE: oac-stg
  CNAME: oac-stg.cdlib.org
  SSLCertARN: arn:aws:acm:us-east-1:777968769372:certificate/f0097032-d6cc-46c0-a6d1-985f3f6cbd55
sceptre_user_data:
  origins:
    - name: arclight
      DomainName: !stack_output_external cinco-stage-arclight-app::LoadBalancerDNS
    - name: arclight_assets
      DomainName: cinco-stage.s3.us-west-2.amazonaws.com
      OriginPath: /arclight_assets
    - name: arclight_errors
      DomainName: cinco-stage.s3.us-west-2.amazonaws.com
      OriginPath: /arclight_errors
    - name: static_findaids
      DomainName: cinco-stage.s3.us-west-2.amazonaws.com
      OriginPath: /static_findaids
  cache_behaviors:
    - PathPattern: "/assets/*"
      TargetOriginId: arclight_assets
      ViewerProtocolPolicy: redirect-to-https
      AllowedMethods:
        - HEAD
        - GET
      CachedMethods:
        - HEAD
        - GET
      ForwardedValues:
        Cookies:
          Forward: none
        QueryString: false
      CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
    - PathPattern: /error.html
      TargetOriginId: arclight_errors
      ViewerProtocolPolicy: redirect-to-https
      AllowedMethods:
        - HEAD
        - GET
        - OPTIONS
      CachedMethods:
        - HEAD
        - GET
      CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
    - PathPattern: /static_findaids/*
      TargetOriginId: static_findaids
      ViewerProtocolPolicy: redirect-to-https
      AllowedMethods:
        - HEAD
        - GET
        - OPTIONS
      CachedMethods:
        - HEAD
        - GET
      CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
