# Generated by Django 5.0.9 on 2024-10-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_repository_repositorylink_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_filing', models.CharField(max_length=255, verbose_name='Collection Title (Filing)')),
                ('local_identifier', models.CharField(max_length=255, verbose_name='Collection Identifier/Call Number')),
                ('date_dacs', models.CharField(max_length=128, verbose_name='Collection Date')),
                ('extent', models.TextField(verbose_name='Extent of Collection')),
                ('abstract', models.TextField()),
                ('language', models.CharField(max_length=3, verbose_name='Language of materials')),
                ('accessrestrict', models.TextField(verbose_name='Access Conditions')),
                ('userestrict', models.TextField(blank=True, verbose_name='Publication Rights')),
                ('acqinfo', models.TextField(blank=True, verbose_name='Acquisition Information')),
                ('scopecontent', models.TextField(verbose_name='Scope and Content of Collection')),
                ('bioghist', models.TextField(blank=True, verbose_name='Biography/Administrative History')),
                ('online_items_url', models.URLField(blank=True, verbose_name='Online Items URL')),
                ('author_statement', models.TextField(blank=True)),
                ('preferred_citation', models.TextField(blank=True)),
                ('processing_information', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressRecordField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('CR', 'Creator'), ('SU', 'Subject'), ('CVR', 'Coverage'), ('TY', 'Type')], max_length=5)),
                ('qualifier', models.CharField(choices=[('P', 'Person'), ('F', 'Family'), ('O', 'Organization'), ('T', 'Topic'), ('GEO', 'Geography'), ('GN', 'Genre'), ('TI', 'Title'), ('OC', 'Occupation')], max_length=5)),
                ('value', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.expressrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FindingAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', models.CharField(max_length=255, unique=True)),
                ('collection_title', models.CharField(max_length=255)),
                ('collection_number', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('express', 'Record Express'), ('ead', 'EAD'), ('ead_pdf', 'EAD with PDF')], max_length=10)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('previewed', 'Previewed'), ('published', 'Published'), ('updated', 'Updated')], default='imported', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ead_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.file')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.repository')),
            ],
        ),
        migrations.AddField(
            model_name='expressrecord',
            name='finding_aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.findingaid'),
        ),
        migrations.CreateModel(
            name='RevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_revised', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.expressrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.file')),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.findingaid')),
            ],
        ),
    ]
