# Generated by Django 5.0.9 on 2024-11-05 16:41

import cincoctrl.findingaids.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementaryfile',
            name='file',
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='ead_file',
            field=models.FileField(blank=True, null=True, upload_to='ead/', validators=[django.core.validators.FileExtensionValidator(['xml']), cincoctrl.findingaids.validators.validate_ead]),
        ),
        migrations.RemoveField(
            model_name='expressrecord',
            name='local_identifier',
        ),
        migrations.AddField(
            model_name='expressrecord',
            name='date_iso',
            field=models.CharField(default=0, max_length=128, verbose_name='Normal Date (ISO)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplementaryfile',
            name='pdf_file',
            field=models.FileField(default=0, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExpressRecordCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_type', models.CharField(choices=[('persname', 'Person'), ('famname', 'Family'), ('corpname', 'Organization')], max_length=10)),
                ('value', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.expressrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressRecordSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('subject', 'Topic'), ('persname', 'Person'), ('famname', 'Family'), ('corpname', 'Organization'), ('geogname', 'Geographic coverage'), ('genreform', 'Genre'), ('title', 'Title'), ('function', 'Function'), ('occupation', 'Occupation')], max_length=10)),
                ('value', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.expressrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='ExpressRecordField',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
