services:
  solr_leader:
    image: cinco/solr
    pull_policy: never
    build:
      context: ./
      dockerfile: ./Dockerfile.solr
      tags:
        - cinco/solr
    ports:
      - "8983:8983"
    environment:
      - REPLICATION_ROLE=leader
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8983/solr/arclight/admin/ping"]
      timeout: 20s
      retries: 10
    #command: ["tail", "-f", "/dev/null"]

  solr_follower:
    image: cinco/solr
    pull_policy: never
    ports:
      - "8984:8983"
    environment:
      - REPLICATION_ROLE=follower
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8983/solr/arclight/admin/ping"]
      timeout: 20s
      retries: 10
    depends_on:
      solr_leader:
        condition: service_healthy
