FROM public.ecr.aws/docker/library/solr:9.6.1

# Copy arclight/solr directory to /opt/solr/server/solr/configsets/arclight
COPY arclight/solr /opt/solr/server/solr/configsets/arclight

COPY solr-docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
