FROM public.ecr.aws/docker/library/solr:9.6.1

# Copy arclight/solr directory to /opt/solr/server/solr/configsets/arclight
COPY arclight/solr /opt/solr/server/solr/configsets/arclight

# Create directories for solr data
RUN mkdir -p /var/solr/data

ENTRYPOINT ["solr-precreate", "arclight", "/opt/solr/server/solr/configsets/arclight"]
