template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output arclight/solr.yaml::ECSCluster
  Namespace: cinco-solr-writer
  VpcId: !environment_variable VPC_ID
  SubnetIDs: !environment_variable SUBNET_IDS
  ContainerImage: 'public.ecr.aws/docker/library/solr:9.6.1'
  ContainerPort: 8983
  ContainerCount: 1
  ContainerEntryPoint: "docker-entrypoint.sh"
  ContainerCommand: "solr-foreground"
  HealthCheckPath: "/solr/#/"

sceptre_user_data:
  Volumes:
    - Name: "cinco-solr-efs-volume"
      EFSVolumeConfiguration:
        FilesystemId: !stack_output arclight/solr-efs.yaml::EfsFileSystemId
        AuthorizationConfig:
          AccessPointId: !stack_output arclight/solr-efs.yaml::EfsAccessPointId
          IAM: ENABLED
        TransitEncryption: ENABLED
  ContainerMountPoints:
    - SourceVolume: "cinco-solr-efs-volume"
      ContainerPath: "/var/solr"
  TaskRole: !stack_output arclight/solr-efs.yaml::EfsTaskRoleArn
  HttpAccessList:
    - !stack_output admin/app-servers.yaml::ServiceSecurityGroup
    # - !stack_output arclight/arclight.yaml::ServiceSecurityGroup
    # - !environment_variable PAD_AIRFLOW_SECURITY_GROUP
