# Generated by Django 5.0.9 on 2025-01-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.findingaid')),
            ],
        ),
    ]
