# Generated by Django 5.0.9 on 2025-01-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0002_validationwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaryfile',
            name='textract_output',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplementaryfile',
            name='textract_status',
            field=models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=50),
        ),
    ]
