# Generated by Django 5.0.9 on 2025-02-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0003_supplementaryfile_textract_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaryfile',
            name='title',
            field=models.CharField(default='Supplemental File', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
