# Generated by Django 5.0.9 on 2025-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0004_supplementaryfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='expressrecord',
            name='language',
        ),
        migrations.AlterField(
            model_name='findingaid',
            name='record_type',
            field=models.CharField(choices=[('express', 'Record Express'), ('ead', 'EAD')], max_length=10),
        ),
        migrations.AddField(
            model_name='expressrecord',
            name='language',
            field=models.ManyToManyField(blank=True, to='findingaids.language'),
        ),
    ]
