# Generated by Django 5.0.9 on 2025-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0005_language_remove_expressrecord_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaryfile',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display sequence'),
            preserve_default=False,
        ),
    ]
