# Generated by Django 5.0.9 on 2025-02-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0006_supplementaryfile_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplementaryfile',
            options={'ordering': ['order', 'pk']},
        ),
    ]
