# Generated by Django 5.0.9 on 2025-03-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0007_alter_language_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('finding_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.findingaid')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
