# Generated by Django 5.0.9 on 2025-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0010_alter_findingaid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='ead_filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
