# Generated by Django 5.0.9 on 2025-10-24 21:34

from django.db import migrations, models


def populate_ead_filesize(apps, schema_editor):
    FindingAid = apps.get_model('findingaids', 'FindingAid')
    for fa in FindingAid.objects.all():
        if fa.ead_file and fa.ead_file.size:
            fa.ead_filesize = fa.ead_file.size
            fa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('findingaids', '0010_alter_findingaid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaid',
            name='ead_filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_ead_filesize, migrations.RunPython.noop),
    ]
