template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output prd/cluster.yaml::ECSCluster
  Namespace: cinco-ctrl-prd
  VpcId: {{ var.prd.VPC_ID }}
  SubnetIDs: {{ var.prd.SUBNET_IDS }}
  ContainerImage: !sub
    - "{container_image}:v0.1.6-beta"
    - container_image: !stack_output prd/cincoctrl/build.yaml::ECRRepository
  ContainerPort: 5000
  HealthCheckPath: '/accounts/login/'
  DBInstanceSecurityGroup: !stack_output prd/cincoctrl/db.yaml::RDSSecurityGroup
sceptre_user_data:
  ContainerEntryPoint: '/entrypoint'
  ContainerCommand: [ "/start" ]
  Description: "CincoCtrl Web Application running in ECS"
  TaskPolicies:
    - !stack_output prd/s3.yaml::Policy
    - !stack_output prd/textract.yaml::QueueConsumerPolicyArn
    - !stack_output_external pad-airflow-access-permissions::Policy
    - !stack_output_external pad-ses-send-policy::Policy
  ContainerEnvironment:
    - POSTGRES_HOST: !stack_output prd/cincoctrl/db.yaml::RDSHostName
    - POSTGRES_PORT: 5432
    - POSTGRES_DB: postgres
    - POSTGRES_USER: {{ var.prd.CINCOCTRL_DB_USERNAME }}
    - POSTGRES_PASSWORD: {{ var.prd.CINCOCTRL_DB_PASSWORD }}
    - DJANGO_SETTINGS_MODULE: config.settings.production
    - DJANGO_SECRET_KEY: {{ var.prd.DJANGO_SECRET_KEY }}
    - DJANGO_ADMIN_URL: {{ var.prd.DJANGO_ADMIN_URL }}
    - DJANGO_AWS_STORAGE_BUCKET_NAME: {{ var.prd.S3_BUCKET_NAME }}
    - WEB_CONCURRENCY: 4
    - DJANGO_SUPERUSER_PASSWORD: {{ var.prd.DJANGO_SUPERUSER_PASSWORD }}
    - SQS_URL: !stack_output prd/textract.yaml::QueueUrl
    - CDL_ARK_NAAN: {{ var.prd.CDL_ARK_NAAN }}
    - CDL_ARK_SHOULDER: {{ var.prd.CDL_ARK_SHOULDER }}
    - EZID_ENDPOINT: {{ var.prd.EZID_ENDPOINT }}
    - EZID_USERNAME: {{ var.prd.EZID_USERNAME }}
    - EZID_PASSWORD: {{ var.prd.EZID_PASSWORD }}
    - SMTP_USER: {{ var.prd.DJANGO_SMTP_USER }}
    - SMTP_PASSWORD: {{ var.prd.DJANGO_SMTP_PASSWORD}}
