template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-ctrl-prd
  Branch: ''
  ECRRepositoryURI: 777968769372.dkr.ecr.us-west-2.amazonaws.com/cinco-ctrl

sceptre_user_data:
  BuildEnvironment:
    - SUBNET_IDS: {{ var.prd.SUBNET_IDS }}
    - SLACK_HOOK: {{ var.prd.SLACK_HOOK }}
  TriggerFilterGroups:
  # A build is triggered if any filter group evaluates to true, which
  # occurs when all the filters in the group evaluate to true.
    - - Type: EVENT
        Pattern: RELEASED
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                install:
                  runtime-versions:
                    python: 3.12
                build:
                  commands:
                    - TAG=`git describe --tags --abbrev=0`
                    - REPO="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com"
                    - NEW_IMAGE="$REPO/cinco-ctrl:$TAG"
                    - cp ./VERSION.txt cincoctrl/CINCO_VERSION.txt
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPO
                    - docker build -t cinco-ctrl:$TAG cincoctrl --file cincoctrl/compose/production/django/Dockerfile
                    - docker tag cinco-ctrl:$TAG $NEW_IMAGE
                    - docker push $NEW_IMAGE
                post_build:
                  commands:
                    - echo "Registering new task definition with image:"
                    - echo $NEW_IMAGE
                    - TASK_FAMILY="cinco-ctrl-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - REGISTERED_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
                    - TD_REVISION=$(echo $REGISTERED_DEFINITION | jq -r '.taskDefinition.revision')
                    - echo "Running Django management commands with new task definition"
                    - chmod +x $CODEBUILD_SRC_DIR/infrastructure/cinco/scripts/ecs_manage.py
                    - python $CODEBUILD_SRC_DIR/infrastructure/cinco/scripts/ecs_manage.py --prd --task-definition $TD_REVISION collectstatic --no-input
                    - python $CODEBUILD_SRC_DIR/infrastructure/cinco/scripts/ecs_manage.py --prd --task-definition $TD_REVISION migrate --no-input
                    - echo "Forcing a new deployment of the service to apply changes"
                    - python $CODEBUILD_SRC_DIR/infrastructure/cinco/scripts/message_slack.py --application cincoctrl --cinco_version $TAG --td_family_revisions "$TASK_FAMILY:$TD_REVISION"
                    - aws ecs update-service --cluster cinco-prd --service cinco-ctrl-prd-service --task-definition $TASK_FAMILY:$TD_REVISION --force-new-deployment
