template:
  path: rds-postgres.yaml
  type: file
parameters:
  DBInstanceClass: db.t4g.small
  Namespace: cinco-ctrl-prd
  VpcId: {{ var.prd.VPC_ID }}
  SubnetIDs: {{ var.prd.SUBNET_IDS }}
  DBUsername: {{ var.prd.CINCOCTRL_DB_USERNAME }}
  DBPassword: {{ var.prd.CINCOCTRL_DB_PASSWORD }}
