
services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: cincoctrl_production_django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
