default: &default
  store_options:
    max_size: <%= 512.megabytes %>
    namespace: <%= Rails.env %>

development:
  database: primary
  <<: *default


test:
  <<: *default

production:
  database: primary
  <<: *default
