#
# downloads.yml - Use the EAD's <unitid> as the primary key and
#                 provide the PDF and/or EAD (.xml) links. The
#                 size value should be a String (shown as-is) or
#                 the number of bytes in the download.
#               - Pass a template key to use a formatted string
#                 which interpolates document accessors into the
#                 url using the %{accessor} syntax.
#               - Pass a size_accessor key to pull the size of
#                 the file from an accessor in the solr document
#
sample_unitid:
  pdf:
    href: ''
    size: '1.23MB'
  ead:
    href: 'https://cinco-stage.s3.amazonaws.com/media/ead/%{eadid}'
    size: 123456
    # size_accessor: 'level'
default:
  disabled: true
  pdf:
    template: ''
  ead:
    template: 'https://cinco-stage.s3.amazonaws.com/media/ead/%{eadid}'
