# Generated by Django 5.0.9 on 2025-03-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('airflow_client', '0001_initial'), ('airflow_client', '0002_alter_jobrun_dag_run_conf_alter_jobrun_dag_run_id_and_more')]

    initial = True

    dependencies = [
        ('findingaids', '0004_supplementaryfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=255)),
                ('dag_run_conf', models.TextField(blank=True, default='')),
                ('airflow_url', models.CharField(max_length=255)),
                ('dag_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('logical_date', models.DateTimeField(blank=True, null=True)),
                ('rest_api_status_code', models.TextField(blank=True)),
                ('rest_api_response', models.TextField(blank=True)),
                ('related_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.findingaid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=255)),
                ('dag_run_conf', models.TextField(blank=True, default='')),
                ('airflow_url', models.CharField(max_length=255)),
                ('dag_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('logical_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='running', max_length=255, verbose_name='Manually update status')),
                ('related_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findingaids.findingaid')),
                ('job_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='airflow_client.jobtrigger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
