# Generated by Django 5.0.9 on 2025-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrun',
            options={'ordering': ['-logical_date']},
        ),
        migrations.AlterModelOptions(
            name='jobtrigger',
            options={'ordering': ['-logical_date']},
        ),
    ]
