# Generated by Django 5.0.9 on 2025-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_client', '0002_alter_jobrun_options_alter_jobtrigger_options'),
        ('findingaids', '0009_alter_findingaid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='related_models',
            field=models.ManyToManyField(related_name='related_%(class)s', to='findingaids.findingaid'),
        ),
        migrations.AddField(
            model_name='jobtrigger',
            name='related_models',
            field=models.ManyToManyField(related_name='related_%(class)s', to='findingaids.findingaid'),
        ),
    ]
