# Generated by Django 5.0.9 on 2025-05-21 18:15

from django.db import migrations


def make_many_related_models(apps, schema_editor):
    """
        Adds the related_model object in JobRun.related_model to the
        many-to-many relationship in JobRun.related_models.
    """
    JobRun = apps.get_model('airflow_client', 'JobRun')
    for jobrun in JobRun.objects.all():
        jobrun.related_models.add(jobrun.related_model)
    
    JobTrigger = apps.get_model('airflow_client', 'JobTrigger')
    for jobtrigger in JobTrigger.objects.all():
        jobtrigger.related_models.add(jobtrigger.related_model)


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_client', '0003_jobrun_related_models_jobtrigger_related_models'),
    ]

    operations = [
        migrations.RunPython(make_many_related_models),
    ]
