# Generated by Django 5.0.9 on 2025-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_client', '0004_auto_20250521_1115'),
        ('findingaids', '0009_alter_findingaid_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='jobtrigger',
            name='related_model',
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='related_models',
            field=models.ManyToManyField(to='findingaids.findingaid'),
        ),
        migrations.AlterField(
            model_name='jobtrigger',
            name='related_models',
            field=models.ManyToManyField(to='findingaids.findingaid'),
        ),
    ]
