# Generated by Django 5.0.9 on 2025-05-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow_client', '0005_remove_jobrun_related_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='job_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airflow_client.jobtrigger'),
        ),
    ]
