template:
  path: rds-postgres.yaml
  type: file
parameters:
  Namespace: cinco-ctrl-stage
  VpcId: !environment_variable VPC_ID
  SubnetIDs: !environment_variable SUBNET_IDS
  DBUsername: !environment_variable CINCOCTRL_DB_USERNAME
  DBPassword: !environment_variable CINCOCTRL_DB_PASSWORD
