template:
  path: rds-postgres.yaml
  type: file
parameters:
  DBInstanceClass: db.t4g.small
  Namespace: cinco-ctrl-stage
  VpcId: {{ var.stage.VPC_ID }}
  SubnetIDs: {{ var.stage.SUBNET_IDS }}
  DBUsername: {{ var.stage.CINCOCTRL_DB_USERNAME }}
  DBPassword: {{ var.stage.CINCOCTRL_DB_PASSWORD }}
