version: "3.7"

# NOTE: this runs solr using the default arclight/blacklight config
# To run solr using the cinco config, use docker-compose.dev.yaml
services:
  solr:
    image: solr:9.5.0
    ports:
      - "8983:8983"
    volumes:
      - ./solr/conf:/opt/solr/conf
      - ./solr-data:/var/solr/data
    environment:
      SOLR_HOME: /var/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
