FROM public.ecr.aws/docker/library/solr:9.6.1

USER root
RUN apt-get update && \
  apt-get -y install --no-install-recommends \
  jq \
  python3 \
  python3-pip \
  unzip \
  sudo \
  cron \
  gosu && \
  pip install boto3 requests && \
  mkdir /opt/solr/arclight

RUN curl -fsSL https://awscli.amazonaws.com/v2/install.sh | sudo bash -s -- --system

# Root-owned files
COPY --chmod=644 solr/leader-backup.cron /etc/cron.d/leader-backup
COPY --chmod=744 solr/entrypoint.sh /entrypoint.sh

# Solr-owned files
COPY --chown=solr:solr solr/conf /opt/solr/server/solr/configsets/arclight/conf
COPY --chown=solr:solr solr/solr.xml /opt/solr/server/solr/solr.xml
COPY --chown=solr:solr solr/solr.in.sh /etc/default/solr.in.sh

COPY --chown=solr:solr --chmod=744 solr/cinco-docker-entrypoint.sh /opt/solr/arclight/cinco-docker-entrypoint.sh
COPY --chown=solr:solr --chmod=744 solr/solr-replication-config.py /opt/solr/arclight/solr-replication-config.py
COPY --chown=solr:solr --chmod=744 solr/leader-backup.py /opt/solr/arclight/leader-backup.py

CMD /entrypoint.sh
