FROM public.ecr.aws/docker/library/solr:9.6.1

USER root
RUN apt-get update && \
  apt-get -y install --no-install-recommends \
  jq \
  python3 \
  python3-pip \
  awscli \
  cron \
  gosu

COPY --chown=solr:solr solr/conf /opt/solr/server/solr/configsets/arclight/conf
COPY --chown=solr:solr solr/solr.xml /opt/solr/server/solr/solr.xml
COPY --chown=solr:solr solr/solr.in.sh /etc/default/solr.in.sh
COPY --chown=solr:solr --chmod=744 solr/leader-backup /opt/solr/docker/scripts/leader-backup

COPY --chmod=744 solr/solr-setup.sh /solr-setup.sh
COPY --chmod=744 solr/solr-replication-config.py /solr-replication-config.py
COPY --chmod=744 solr/entrypoint.sh /entrypoint.sh
COPY --chmod=644 solr/leader-backup.cron /etc/cron.d/leader-backup

CMD /entrypoint.sh
