# Generated by Django 5.0.9 on 2024-12-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_repository_repositorylink_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
