# Generated by Django 5.0.9 on 2025-02-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_repository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
