# Generated by Django 5.0.9 on 2025-02-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_repository_logo'),
        ('users', '0004_alter_repository_phone'),
    ]

    operations = [
    ]
