# Generated by Django 5.0.9 on 2025-03-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_repository_latitude_repository_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='aeon_url',
            new_name='aeon_request_url',
        ),
        migrations.AddField(
            model_name='repository',
            name='aeon_request_mappings',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
