# Generated by Django 5.0.9 on 2025-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_aeon_url_repository_aeon_request_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name'], 'verbose_name_plural': 'repositories'},
        ),
    ]
