# Generated by Django 5.0.9 on 2025-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_repository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='logo',
            field=models.ImageField(blank=True, upload_to='repo-logos/'),
        ),
    ]
