# Generated by Django 5.0.9 on 2025-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_repository_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='auto_index',
            field=models.BooleanField(default=True),
        ),
    ]
