template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-solr-prd
  Branch: ''
  ECRRepositoryURI: !stack_output stage/solr/build.yaml::ECRRepository

sceptre_user_data:
  TriggerFilterGroups:
  # A build is triggered if any filter group evaluates to true, which
  # occurs when all the filters in the group evaluate to true.
    - - Type: EVENT
        Pattern: RELEASED
  BuildEnvironment:
    - SLACK_HOOK: {{ var.prd.SLACK_HOOK }}
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                install:
                  runtime-versions:
                    python: 3.12
                pre_build:
                  commands:
                    - cd $CODEBUILD_SRC_DIR/arclight
                build:
                  commands:
                    - TAG=`git describe --tags --abbrev=0`
                    - REPO="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com"
                    - NEW_IMAGE="$REPO/cinco-solr:$TAG"
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPO
                    - docker build -t cinco-solr:$TAG . --file Dockerfile.solr
                    - docker tag cinco-solr:$TAG $NEW_IMAGE
                    - docker push $NEW_IMAGE
                post_build:
                  commands:
                    - echo "Updating solr leader task definition"
                    - TASK_FAMILY="cinco-solr-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - REGISTERED_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
                    - TD_REVISION=$(echo $REGISTERED_DEFINITION | jq -r '.taskDefinition.revision')
                    - echo "Please update solr leader service, task definition revision:"
                    - echo $TD_REVISION
                    - LEADER="cinco-solr-prd:$TD_REVISION"
                    # - aws ecs update-service --cluster cinco-prd --service cinco-solr-prd-service --task-definition $TASK_FAMILY:$TD_REVISION --force-new-deployment
                    ##### Update solr follower 1 task definition #####
                    - echo "Updating solr follower 1 task definition"
                    - TASK_FAMILY="cinco-solr-follower-1-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - REGISTERED_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
                    - TD_REVISION=$(echo $REGISTERED_DEFINITION | jq -r '.taskDefinition.revision')
                    - echo "Please update solr follower 1 service, task definition revision:"
                    - echo $TD_REVISION
                    - FOLLOWER_1="cinco-solr-follower-1-prd:$TD_REVISION"
                    # - aws ecs update-service --cluster cinco-prd --service cinco-solr-follower-1-prd-service --task-definition $TASK_FAMILY:$TD_REVISION --force-new-deployment
                    ##### Update solr follower 2 task definition #####
                    - echo "Updating solr follower 2 task definition"
                    - TASK_FAMILY="cinco-solr-follower-2-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - REGISTERED_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
                    - TD_REVISION=$(echo $REGISTERED_DEFINITION | jq -r '.taskDefinition.revision')
                    - echo "Please update solr follower 2 service, task definition revision:"
                    - echo $TD_REVISION
                    - FOLLOWER_2="cinco-solr-follower-2-prd:$TD_REVISION"
                    # - aws ecs update-service --cluster cinco-prd --service cinco-solr-follower-2-prd-service --task-definition $TASK_FAMILY:$TD_REVISION --force-new-deployment
                    ###### Message Slack #####
                    - python $CODEBUILD_SRC_DIR/infrastructure/cinco/scripts/message_slack.py --application solr --cinco_version $TAG --td_family_revisions $LEADER $FOLLOWER_1 $FOLLOWER_2
