template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-solr-prd
  Branch: ''
  ECRRepositoryURI: !stack_output stage/solr/build.yaml::ECRRepository

sceptre_user_data:
  TriggerFilterGroups:
  # A build is triggered if any filter group evaluates to true, which
  # occurs when all the filters in the group evaluate to true.
    - - Type: EVENT
        Pattern: RELEASED
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                pre_build:
                  commands:
                    - cd $CODEBUILD_SRC_DIR/arclight
                build:
                  commands:
                    - TAG=`git describe --tags --abbrev=0`
                    - REPO="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com"
                    - NEW_IMAGE="$REPO/cinco-solr:$TAG"
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPO
                    - docker build -t cinco-solr:$TAG . --file Dockerfile.solr
                    - docker tag cinco-solr:$TAG $NEW_IMAGE
                    - docker push $NEW_IMAGE
                post_build:
                  commands:
                    - TASK_FAMILY="cinco-solr-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION"
                    # - aws ecs update-service --cluster cinco-prd --service cinco-solr-prd-service --force-new-deployment
