template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output prd/cluster.yaml::ECSCluster
  Namespace: cinco-solr-prd
  VpcId: {{ var.prd.VPC_ID }}
  SubnetIDs: {{ var.prd.SUBNET_IDS }}
  ContainerImage: !stack_output prd/solr/build.yaml::ECRRepository
  ContainerPort: 8983
  ContainerCount: 1
  HealthCheckPath: "/solr/arclight/admin/ping"
  # old container must be stopped before new one is started,
  # otherwise we get an error about index dir locking from Solr
  ServiceTaskMaximumPercent: 100
  ServiceTaskMinimumHealthyPercent: 0
  HealthCheckGracePeriodSeconds: 600
  Cpu: 2048
  Memory: 4096 # SOLR_HEAP in arclight/solr/solr.in.sh should be set to 50% of this

sceptre_user_data:
  ApplicationType: internal
  ContainerEntryPoint: "/cinco-docker-entrypoint.sh"
  Volumes:
    - Name: "cinco-solr-efs-volume"
      EFSVolumeConfiguration:
        FilesystemId: !stack_output prd/solr/efs.yaml::EfsFileSystemId
        AuthorizationConfig:
          AccessPointId: !stack_output prd/solr/efs.yaml::EfsAccessPointId
          IAM: ENABLED
        TransitEncryption: ENABLED
  ContainerMountPoints:
    - SourceVolume: "cinco-solr-efs-volume"
      ContainerPath: "/var/solr"
  TaskPolicies:
    - !stack_output prd/solr/efs.yaml::EfsReaderPolicyArn
  ContainerEnvironment:
    - REPLICATION_ROLE: leader
  ContainerPortName: solr
  ContainerPortAppProtocol: http
  ServiceConnectConfiguration:
    Enabled: true
    Services:
      - PortName: solr
        DiscoveryName: solr_leader
        ClientAliases:
          - Port: 8983
            DnsName: solr_leader.cinco-prd
        # We have to specify an ingress port override, otherwise the target group healthcheck fails
        IngressPortOverride: 8984
  AdditionalServiceSecurityGroupIngressRules:
    - description: Allow access from solr-follower-1 container
      from_port: 8984
      to_port: 8984
      security_group_id: !stack_output prd/solr/solr-follower-1.yaml::ServiceSecurityGroup
    - description: Allow access from solr-follower-2 container
      from_port: 8984
      to_port: 8984
      security_group_id: !stack_output prd/solr/solr-follower-2.yaml::ServiceSecurityGroup
  # This healthcheck is more accurate than the target group healthcheck
  ContainerHealthCheck: |-
    Command:
                  - "CMD-SHELL"
                  - "curl -sf http://localhost:8983/solr/arclight/admin/ping?wt=json | jq '.status' | grep -iq \"ok\" || exit 1"
                StartPeriod: 15
                Interval: 10
                Timeout: 5
                Retries: 3
  # HttpAccessList:
  #   - !stack_output prd/cincoctrl/app.yaml::ServiceSecurityGroup
  #   # - !stack_output prd/arclight/app.yaml::ServiceSecurityGroup
  #   # - {{ var.prd.PAD_AIRFLOW_SECURITY_GROUP }}
