template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output stage/cluster.yaml::ECSCluster
  Namespace: cinco-ctrl
  VpcId: !environment_variable VPC_ID
  SubnetIDs: !environment_variable SUBNET_IDS
  ContainerImage: !stack_output stage/ctrl-build.yaml::ECRRepository
  ContainerPort: 5000
  ContainerEntryPoint: '/entrypoint'
  HealthCheckPath: '/'
  ContainerCommand: "/start"
  DBInstanceSecurityGroup: !stack_output stage/ctrl-db.yaml::RDSSecurityGroup
sceptre_user_data:
  Description: "CincoCtrl Web Application running in ECS"
  TaskPolicies:
    - !stack_output stage/s3-access.yaml::Policy
  ContainerEnvironment:
    - POSTGRES_HOST: !stack_output stage/ctrl-db.yaml::RDSHostName
    - POSTGRES_PORT: 5432
    - POSTGRES_DB: postgres
    - POSTGRES_USER: !environment_variable DB_USERNAME
    - POSTGRES_PASSWORD: !environment_variable DB_PASSWORD
    - DJANGO_SETTINGS_MODULE: config.settings.stage
    - DJANGO_SECRET_KEY: !environment_variable DJANGO_SECRET_KEY
    - DJANGO_ADMIN_URL: !environment_variable DJANGO_ADMIN_URL
    - DJANGO_AWS_STORAGE_BUCKET_NAME: !environment_variable S3_BUCKET
    - WEB_CONCURRENCY: 4
    - DJANGO_SUPERUSER_PASSWORD: !environment_variable DJANGO_SUPERUSER_PASSWORD
    - SQS_URL: !stack_output stage/sqs.yaml::QueueUrl
