template:
  path: grant-airflow.j2
  type: file

sceptre_user_data:
  logs:
    - !stack_output_external cinco-stage-cincoctrl-app::LogGroup
    - !stack_output_external cinco-stage-arclight-app::LogGroup
    - !stack_output_external cinco-prd-cincoctrl-app::LogGroup
    - !stack_output_external cinco-prd-arclight-app::LogGroup
  stacks:
    - cinco-stage-solr-solr
    - cinco-stage-arclight-app
    - cinco-prd-solr-solr
    - cinco-prd-arclight-app
