template:
  path: ecs-webapp.j2
  type: file
parameters:
  Namespace: cinco-admin
  VpcId: !environment_variable VPC_ID
  SubnetIDs: !environment_variable SUBNET_IDS
  ContainerImage: !stack_output admin/codebuild.yaml::ECRRepository
  ContainerPort: 5000
  ContainerEntryPoint: '/entrypoint'
  HealthCheckPath: '/'
  ContainerCommand: "/start"
  DBInstanceSecurityGroup: !stack_output admin/db.yaml::RDSSecurityGroup
sceptre_user_data:
  ContainerEnvironment:
    - Name: POSTGRES_HOST
      Value: !stack_output admin/db.yaml::RDSHostName
    - Name: POSTGRES_PORT
      Value: 5432
    - Name: POSTGRES_DB
      Value: postgres
    - Name: POSTGRES_USER
      Value: !environment_variable DB_USERNAME
    - Name: POSTGRES_PASSWORD
      Value: !environment_variable DB_PASSWORD
    - Name: DJANGO_SETTINGS_MODULE
      Value: config.settings.production
    - Name: DJANGO_SECRET_KEY
      Value: !environment_variable DJANGO_SECRET_KEY
    - Name: DJANGO_ADMIN_URL
      Value: !environment_variable DJANGO_ADMIN_URL
    - Name: DJANGO_AWS_STORAGE_BUCKET_NAME
      Value: !environment_variable S3_BUCKET
    - Name: WEB_CONCURRENCY
      Value: 4
