AWSTemplateFormatVersion: 2010-09-09

Description: EFS Volume

Parameters:
  Namespace:
    Description: The namespace for the EFS Volume
    Type: String
  VpcId:
    Description: The VPC the EFS volume will exist in
    Type: AWS::EC2::VPC::Id
  PrivateSubnetId1:
    Description: The first private subnet the EFS volume will exist in
    Type: AWS::EC2::Subnet::Id
  PrivateSubnetId2:
    Description: The second private subnet the EFS volume will exist in
    Type: AWS::EC2::Subnet::Id
  EFSAccessPointUserGroup:    # "8983"
    Description: The user and group for the EFS Access Point
    Type: String
  EFSAccessPointPath:         # "/var/solr"
    Description: The path for the EFS Access Point
    Type: String
  ThroughputMode:
    Description: Throughput mode for the file system
    Type: String
    Default: elastic

Resources:
  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${Namespace}-efs
      GroupDescription: !Sub Security Group for ${Namespace} EFS
      SecurityGroupIngress:
        - Description: Allow inbound traffic NFS traffic
          ToPort: 2049
          FromPort: 2049
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - Description: Allow outbound NFS traffic
          ToPort: 2049
          FromPort: 2049
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      VpcId: !Ref 'VpcId'

  EfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: !Sub ${Namespace}-efs-volume
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      ThroughputMode: !Ref ThroughputMode
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  EfsAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EfsFileSystem
      PosixUser:
        Uid: !Ref EFSAccessPointUserGroup
        Gid: !Ref EFSAccessPointUserGroup
      RootDirectory:
        CreationInfo:
          OwnerGid: !Ref EFSAccessPointUserGroup
          OwnerUid: !Ref EFSAccessPointUserGroup
          Permissions: "0755"
        Path: !Ref EFSAccessPointPath

  EfsMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Ref PrivateSubnetId1
      SecurityGroups:
        - !Ref EfsSecurityGroup

  EfsMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Ref PrivateSubnetId2
      SecurityGroups:
        - !Ref EfsSecurityGroup

  EfsReaderPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: !Sub ${Namespace}-reader-policy
        Path: "/"
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: EFSAccess
              Effect: Allow
              Action:
                - elasticfilesystem:ClientMount
                - elasticfilesystem:DescribeMountTargets
                - elasticfilesystem:DescribeFileSystems
              Resource: !GetAtt EfsFileSystem.Arn

  EfsWriterPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: !Sub ${Namespace}-writer-policy
        Path: "/"
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: EFSAccess
              Effect: Allow
              Action:
                - elasticfilesystem:ClientWrite
              Resource: !GetAtt EfsFileSystem.Arn

Outputs:
  EfsFileSystemId:
    Description: The ID of the EFS file system
    Value: !Ref EfsFileSystem

  EfsAccessPointId:
    Description: The ID of the EFS access point
    Value: !Ref EfsAccessPoint

  EfsReaderPolicyArn:
    Description: The ARN of the EFS task role
    Value: !GetAtt EfsReaderPolicy.PolicyArn

  EfsWriterPolicyArn:
    Description: The ARN of the EFS task role
    Value: !GetAtt EfsWriterPolicy.PolicyArn
