AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda execution role

Parameters:
  Namespace:
    Type: String
    Description: The base name used for this stack

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Namespace}-lambda-execution-role
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]

  ExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Namespace}-lambda-execution-policy
      Path: "/"
      Roles: [ !Ref ExecutionRole ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: LoggingAccess
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"

Outputs:
  ExecutionRoleArn:
    Value: !GetAtt ExecutionRole.Arn
