Parameters:
  Namespace:
    Description: The namespace for the stack
    Type: String
  BucketName:
    Description: The name of the S3 bucket to grant access to
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Namespace}-role
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ "sts:AssumeRole" ]
            Condition:
              ArnLike:
                aws:SourceArn:
                  - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:*"
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  Policy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: !Sub ${Namespace}-policy
        Path: "/"
        Roles: [ !Ref Role ]
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: S3Access
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
                - s3:DeleteObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
                - !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"

Outputs:
  TaskRole:
    Description: The ARN of the task role with s3 permissions
    Value: !GetAtt Role.Arn
