template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output_external cinco-stage-cluster::ECSCluster
  Namespace: cinco-solr-stage
  VpcId: {{ var.stage.VPC_ID }}
  SubnetIDs: {{ var.stage.SUBNET_IDS }}
  ContainerImage: !stack_output_external cinco-stage-solr-build::ECRRepository
  ContainerPort: 8983
  ContainerCount: 1
  HealthCheckPath: "/solr/arclight/admin/ping"
  # old container must be stopped before new one is started,
  # otherwise we get an error about index dir locking from Solr
  ServiceTaskMaximumPercent: 100
  ServiceTaskMinimumHealthyPercent: 0
  HealthCheckGracePeriodSeconds: 600
  Cpu: 2048
  Memory: 4096 # SOLR_HEAP in arclight/solr/solr.in.sh should be set to 50% of this

sceptre_user_data:
  ApplicationType: internal
  ContainerEntryPoint: "/cinco-docker-entrypoint.sh"
  Volumes:
    - Name: "cinco-solr-efs-volume"
      EFSVolumeConfiguration:
        FilesystemId: !stack_output_external cinco-stage-solr-efs::EfsFileSystemId
        AuthorizationConfig:
          AccessPointId: !stack_output_external cinco-stage-solr-efs::EfsAccessPointId
          IAM: ENABLED
        TransitEncryption: ENABLED
  ContainerMountPoints:
    - SourceVolume: "cinco-solr-efs-volume"
      ContainerPath: "/var/solr"
  TaskPolicies:
    - !stack_output_external cinco-stage-solr-efs::EfsReaderPolicyArn
  ContainerEnvironment:
    - REPLICATION_ROLE: leader
  ContainerPortName: solr
  ContainerPortAppProtocol: http
  ServiceConnectConfiguration:
    Enabled: true
    Services:
      - PortName: solr
        DiscoveryName: solr_leader
        ClientAliases:
          - Port: 8983
            DnsName: solr_leader.cinco-stage
        # We have to specify an ingress port override, otherwise the target group healthcheck fails
        IngressPortOverride: 8984
  # This healthcheck is more accurate than the target group healthcheck
  ContainerHealthCheck: |-
    Command:
                  - "CMD-SHELL"
                  - "curl -sf http://localhost:8983/solr/arclight/admin/ping?wt=json | jq '.status' | grep -iq \"ok\" || exit 1"
                StartPeriod: 15
                Interval: 10
                Timeout: 5
                Retries: 3
  # HttpAccessList:
  #   - !stack_output_external cinco-stage-cincoctrl-app::ServiceSecurityGroup
  #   # - !stack_output_external cinco-stage-arclight-app::ServiceSecurityGroup
  #   # - {# var.stage.PAD_AIRFLOW_SECURITY_GROUP #}
