template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output stage/cluster.yaml::ECSCluster
  Namespace: cinco-solr-follower-1-stage
  VpcId: !environment_variable VPC_ID
  SubnetIDs: !environment_variable SUBNET_IDS
  ContainerImage: !stack_output stage/solr/build.yaml::ECRRepository
  ContainerPort: 8983
  ContainerCount: 1
  HealthCheckPath: "/solr/arclight/admin/ping"
  ServiceTaskMaximumPercent: 100
  ServiceTaskMinimumHealthyPercent: 0
  HealthCheckGracePeriodSeconds: 300

sceptre_user_data:
  ApplicationType: internal
  ContainerEntryPoint: "/cinco-docker-entrypoint.sh"
  #ContainerEntryPoint: '"tail", "-f", "/dev/null"'
  Volumes:
    - Name: "cinco-solr-follower-efs-volume"
      EFSVolumeConfiguration:
        FilesystemId: !stack_output stage/solr/efs.yaml::EfsFileSystemId
        AuthorizationConfig:
          AccessPointId: !stack_output stage/solr/efs-follower-access-points.yaml::EfsAccessPointId1
          IAM: ENABLED
        TransitEncryption: ENABLED
  ContainerMountPoints:
    - SourceVolume: "cinco-solr-follower-efs-volume"
      ContainerPath: "/var/solr"
  TaskPolicies:
    - !stack_output stage/solr/efs.yaml::EfsReaderPolicyArn
  ContainerEnvironment:
    - REPLICATION_ROLE: follower
    - SOLR_LEADER_URL: http://solr_leader.cinco-stage:8983/solr/arclight/replication
  ContainerPortName: solr
  ContainerPortAppProtocol: http
  ServiceConnectConfiguration:
    Enabled: true
    Services:
      - PortName: solr
        DiscoveryName: solr_follower
        ClientAliases:
          - Port: 8983
            DnsName: solr_follower.cinco-stage
        IngressPortOverride: 8984
