template:
  path: ecs-webapp.j2
  type: file
parameters:
  ClusterName: !stack_output prd/cluster.yaml::ECSCluster
  Namespace: cinco-arclight-prd
  VpcId: {{ var.prd.VPC_ID }}
  SubnetIDs: {{ var.prd.SUBNET_IDS }}
  ContainerImage: !stack_output prd/arclight/build.yaml::ECRRepository
  ContainerPort: 3000
  HealthCheckPath: '/'
  DBInstanceSecurityGroup: !stack_output prd/arclight/db.yaml::RDSSecurityGroup
sceptre_user_data:
  ContainerEntryPoint: "/rails/bin/docker-entrypoint"
  ContainerCommand:
    - "./bin/rails"
    - "server"
  Description: "Arclight Web Application running in ECS"
  ContainerEnvironment:
    - RAILS_MASTER_KEY: {{ var.prd.RAILS_MASTER_KEY }}
    - S3_BUCKET: {{ var.prd.S3_BUCKET_NAME }}
    - SOLR_URL: !sub
      - "http://{solr_url}/solr/{core_name}"
      # The load balancer for both followers is created as part of the solr-follower-1 stack
      - solr_url: !stack_output prd/solr/solr-follower-1.yaml::LoadBalancerDNS
        core_name: arclight
    - POSTGRES_HOST: !stack_output prd/arclight/db.yaml::RDSHostName
    - POSTGRES_PORT: 5432
    - POSTGRES_DB: postgres
    - POSTGRES_USER: {{ var.prd.ARCLIGHT_DB_USERNAME }}
    - POSTGRES_PASSWORD: {{ var.prd.ARCLIGHT_DB_PASSWORD }}
    - MATOMO_SITE_ID: {{ var.prd.MATOMO_SITE_ID }}
  GrantHttpAccessFromThisServiceTo:
    - !stack_output prd/solr/solr.yaml::LoadBalancerSecurityGroup
