template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-arclight-prd
  Branch: main
  ECRRepositoryURI: !stack_output stage/arclight/codebuild::ECRRepository

sceptre_user_data:
  BuildEnvironment:
    - SUBNET_IDS: {{ var.prd.SUBNET_IDS }}
  TriggerFilterGroups:
    - - Type: EVENT
        Pattern: PUSH
      - Type: HEAD_REF
        Pattern: ^refs/heads/main$
        ExcludeMatchedPattern: false
      - Type: FILE_PATH
        Pattern: arclight/.*
        ExcludeMatchedPattern: false
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                build:
                  commands:
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com
                    - docker build -t cinco-arclight arclight --file arclight/Dockerfile
                    - docker tag cinco-arclight:latest ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/cinco-arclight:latest
                    - docker push ${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/cinco-arclight:latest
                # post_build:
                #   commands:
                #     - aws ecs update-service --cluster cinco-prd --service cinco-arclight-prd-service --force-new-deployment
