template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-arclight-prd
  Branch: ''
  ECRRepositoryURI: !stack_output stage/arclight/build.yaml::ECRRepository

sceptre_user_data:
  BuildEnvironment:
    - SUBNET_IDS: {{ var.prd.SUBNET_IDS }}
  TriggerFilterGroups:
  # A build is triggered if any filter group evaluates to true, which
  # occurs when all the filters in the group evaluate to true.
    - - Type: EVENT
        Pattern: RELEASED
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                build:
                  commands:
                    - TAG=`git describe --tags --abbrev=0`
                    - REPO="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com"
                    - NEW_IMAGE="$REPO/cinco-arclight:$TAG"
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPO
                    - docker build -t cinco-arclight:$TAG arclight --file arclight/Dockerfile
                    - docker tag cinco-arclight:$TAG $NEW_IMAGE
                    - docker push $NEW_IMAGE
                post_build:
                  commands:
                    - TASK_FAMILY="cinco-arclight-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - REGISTERED_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
                    - TD_REVISION=$(echo $REGISTERED_DEFINITION | jq -r '.taskDefinition.revision')
                    - aws ecs update-service --cluster cinco-prd --service cinco-arclight-prd-service --task-definition $TASK_FAMILY:$TD_REVISION --force-new-deployment
