template:
  path: codebuild.j2
  type: file
parameters:
  GitHubRepo: https://github.com/ucldc/cinco
  Namespace: cinco-arclight-prd
  Branch: ''
  ECRRepositoryURI: 777968769372.dkr.ecr.us-west-2.amazonaws.com/cinco-arclight

sceptre_user_data:
  BuildEnvironment:
    - SUBNET_IDS: {{ var.prd.SUBNET_IDS }}
    - SLACK_HOOK: {{ var.prd.SLACK_HOOK }}
  TriggerFilterGroups:
  # A build is triggered if any filter group evaluates to true, which
  # occurs when all the filters in the group evaluate to true.
    - - Type: EVENT
        Pattern: RELEASED
  build_spec: |-
    !Sub >-
              version: 0.2

              phases:
                install:
                  runtime-versions:
                    python: 3.12
                build:
                  commands:
                    - TAG=`git describe --tags --abbrev=0`
                    - REPO="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com"
                    - NEW_IMAGE="$REPO/cinco-arclight:$TAG"
                    - cp ./VERSION.txt arclight/CINCO_VERSION.txt
                    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REPO
                    - docker build -t cinco-arclight:$TAG arclight --file arclight/Dockerfile
                    - docker tag cinco-arclight:$TAG $NEW_IMAGE
                    - docker push $NEW_IMAGE
                post_build:
                  commands:
                    - docker run -d --name arclight-tail-dev-null cinco-arclight:$TAG tail -f /dev/null
                    - docker cp arclight-tail-dev-null:/rails/public/assets ./public_assets
                    - aws s3 cp --recursive ./public_assets s3://cinco-prd/arclight_assets/assets
                    - docker stop arclight-tail-dev-null
                    - TASK_FAMILY="cinco-arclight-prd"
                    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY")
                    - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
                    - REGISTERED_DEFINITION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
                    - TD_REVISION=$(echo $REGISTERED_DEFINITION | jq -r '.taskDefinition.revision')
                    - python $CODEBUILD_SRC_DIR/infrastructure/cinco/scripts/message_slack.py --application arclight --cinco_version $TAG --td_family_revisions "$TASK_FAMILY:$TD_REVISION"
                    - aws ecs update-service --cluster cinco-prd --service cinco-arclight-prd-service --task-definition $TASK_FAMILY:$TD_REVISION --force-new-deployment
  additional_policy_statements: |-
    - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !Sub arn:aws:s3:::cinco-prd*
