template:
  path: rds-postgres.yaml
  type: file
parameters:
  DBInstanceClass: db.t4g.small
  Namespace: cinco-arclight-prd
  VpcId: !environment_variable VPC_ID
  SubnetIDs: !environment_variable SUBNET_IDS
  DBUsername: !environment_variable ARCLIGHT_DB_USERNAME
  DBPassword: !environment_variable ARCLIGHT_DB_PASSWORD
