#!/bin/bash
set -e

# don't back up if no changes since last backup
if aws s3 ls s3://cinco-dev/solr_backups/index_version.txt >/dev/null 2>&1; then
    last_snapshot_version=$(aws s3 cp s3://cinco-dev/solr_backups/index_version.txt -)
    solr_resp=$(curl -s "http://localhost:8983/solr/arclight/replication?command=details")
    index_version=$(echo "$solr_resp" | jq -r '.details.indexVersion')
    if [[ "$last_snapshot_version" == "$index_version" ]]; then
        echo "last snapshot version equals current index version; no backup needed"
        exit 0
    else
        echo "making a new backup!"
    fi
else
    echo "no index version in s3"
fi

# start backup
solr_resp=$(curl -s "http://localhost:8983/solr/arclight/replication?command=backup&repository=s3&location=solr_backups")
respstatus=$(echo "$solr_resp" | jq -r '.status')

# create a log message function that takes a status, a message, and a solr resp, and outputs a JSON object with those values
log_msg() {
    local arclight_backup_status="$1"
    local message="$2"
    local solr_resp="$3"
    jq -nc --arg arclight_backup_status "$arclight_backup_status" --arg message "$message" --argjson solr_resp "$solr_resp" '$ARGS.named'
}

# if respstatus isn't "OK", then something went wrong trying to start the backup; log:
if [[ "$respstatus" != "OK" ]]; then
    echo $(log_msg "failed" "error issuing replication?command=backup" "$solr_resp")
    exit 1
fi

# wait up to {timeout} for backup to complete successfully, checking every {polling} seconds
start_time=$(date +%s)
timeout_seconds=60
polling_seconds=5
while true; do
    # curl for details on the backup status
    solr_resp=$(curl -s "http://localhost:8983/solr/arclight/replication?command=details")
    backup=$(echo "$solr_resp" | jq -r '.details.backup')
    backupstatus=$(echo "$backup" | jq -r '.status')

    # if backup success, log a message and exit
    if [[ "$backupstatus" == "success" ]]; then
        # store the most recently backed up index version in s3 and perform snapshot rotation
        index_version=$(echo "$solr_resp" | jq -r '.details.indexVersion')
        echo "$index_version" | aws s3 cp - s3://cinco-dev/solr_backups/index_version.txt
        python3 /snapshot-rotation.py
        if [[ "$?" != 0 ]]; then
            echo $(log_msg "error" "s3 snapshot rotation failed" "{}")
        fi

        # calculate the elapsed time for the backup
        starttime=$(date -d $(echo "$backup" | jq -r '.startTime') +%s)
        endtime=$(date -d $(echo "$backup" | jq -r '.endTime') +%s)
        elapsedtime=$(( endtime - starttime ))
        backupname=$(echo "$backup" | jq -r '.directoryName')
        echo $(log_msg "success" "Backup completed successfully in ${elapsedtime}s at ${backupname}" "$backup")
        break
    elif [[ "$backupstatus" == "failed" ]]; then
        echo $(log_msg "failed" "Solr backup failed - see solr response for details" "$solr_resp")
        exit 1
    else
        sleep $polling_seconds
    fi

    # if the timeout has been reached, log a message and exit
    now=$(date +%s)
    elapsed=$(( now - start_time ))
    if (( elapsed >= timeout_seconds )); then
        echo $(log_msg "unknown" "backup did not complete within ${timeout_seconds}s" "$solr_resp")
        exit 1
    fi
done
