template:
  path: grant-airflow.j2
  type: file

sceptre_user_data:
  logs:
    - !stack_output prd/cincoctrl/app.yaml::LogGroup
    - !stack_output prd/arclight/app.yaml::LogGroup
  stacks:
    - cinco-prd-solr-solr
    - cinco-prd-arclight-app
